Import('env')

v_env = env.Clone()

v_env.AppendUnique(
	LIBS = ['microstranparser'] + env.get('SOQT_LIBS')
	,LIBPATH = ['..'] + env.get('SOQT_LIBPATH')
	,CPPPATH = ['..'] + env.get('SOQT_CPPPATH')
	,CPPDEFINES = env.get('SOQT_CPPDEFINES')
)

srcs = Split("""
	render.cpp
	arc2iv.cpp
""")

env['PROGS'].append( 
	v_env.Program("../arc2iv",srcs)
)

#env['PROGS'].append( 
#	v_env.Program("../iv2vrml",['iv2vrml.cpp'])
#)

env['PROGS'].append( 
	v_env.Program("../forcebalance",['forcebalance.cpp','render.cpp'])
)


