.TH frame3dd-config 1 "April 21, 2007" frame3dd "User's Manual"
.SH NAME
frame3dd-config \- Output configuration data for frame3dd

.SH SYNOPSIS
.B Usage: frame3dd-config [--help,...]

Options:
  --version   show program's version number and exit
  -h, --help  show this help message and exit
  --libs      show linker flags (for frame3dd libraries)
  --cppflags  show C pre-processor flags (for frame3dd header files)

.SH DESCRIPTION

\fBframe3dd-config\fR can be used when building packages that depend
on frame3dd, ensuring that you are using the correct C preprocessor or
library linking flags for the particular system you're on.

\fBframe3dd\fR is a program for calculating the performance of
structural frames and trusses in 2D and 3D. For more information see
the frame3dd website at

http://frame3dd.sourceforge.net/

