#!/usr/bin/python

Import('env')

srcs = Split("""
	new.c  
	parse.c 
	print.c
	CharactersInDouble.c
	error.c 
	array.c 
	case.c 
	model.c 
	modelparser.c 
	displacements.c
	displacementparser.c
	sections.c
	sectionsparser.c
	vec3.c
	ctrans.c
	forces.c
	forceparser.c
""")
# bdd.c row.c  table.c  print.c   iter.c  list.c  

libenv = env.Clone()
libenv.AppendUnique(LIBS = ['m'])

lib = libenv.SharedLibrary("../microstranparser",srcs)

microst = env.Program('microst',['main.c'],LIBS=["microstranparser"],LIBPATH=[".."])

dumpsections = env.Program('dumpsections',['dumpsections.c'],LIBS=["microstranparser"],LIBPATH=[".."])

dumpforces = env.Program('dumpforces',['dumpforces.c'],LIBS=["microstranparser"],LIBPATH=[".."])

dumpcases = env.Program('dumpcases',['dumpcases.c'],LIBS=["microstranparser"],LIBPATH=[".."])

env['PROGS'] += [microst, dumpsections, dumpforces, dumpcases, lib]

