Import('env')

srcs = [
	'frame.c','lu_dcmp.c','ldl_dcmp.c','nrutil.c','eig.c'
	, 'frm_io.c'
	, 'coordtrans.c'
]

frame = env.Program('frame',srcs + ['main.c'], LIBS=['m'])

bindir=Dir(env.subst("$INSTALL_ROOT$INSTALL_BIN"))
env.Install(bindir,frame);

#libdir=Dir(env.subst("$INSTALL_ROOT$INSTALL_LIB"))
#env.Install(bindir,lib);

env['installdirs'] += [bindir]

print "CCFLAGS =",env['CCFLAGS']
